name: MaxDaves
favicon: null
layout_spectrum: 0.27064778353087604
typography_spectrum: 0.006674547679722309
title: WHERE THE CREATIVE AND ANALYTICAL UNIFY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6426815662998706
  lightness: 0.7957797045819461
  saturation: 0.1628095859196037
  rhythmicContrast: 0.9238822830375284
purpose: []
